name: post_challenge
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.1.1
  bloc_test: ^10.0.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  mockito: ^5.4.6
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  flutter_screenutil: ^5.9.3
  dartz: any
  internet_connection_checker_plus: ^2.0.0
  dio: ^5.8.0+1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^3.0.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
